export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SET_MOVIE_LIST = 'SET_MOVIE_LIST';
export const EDIT_MOVIE_SUBMIT = 'EDIT_MOVIE_SUBMIT';
export const ADD_MOVIE_SUBMIT ='ADD_MOVIE_SUBMIT';
export const DELETE_MOVIE= 'DELETE_MOVIE';
export const FORM_ERROR ='FORM_ERROR';
export const CLEAR_FORM_ERROR= 'CLEAR_FORM_ERROR';